### ISSUE TITLE
Unity+WindowsPhone dll conflict with Parse dll

### ISSUE THREAD

**Issue by sercante** [ParsePlatform/Parse-SDK-dotNET#126]
Hi, I'm currently using Parse for my Unity application and it's already working on Android and Ios, now we are trying to make it work on Windows phone 8.1, but there is a conflict with the dll files. 

Assets\Scripts\3rd Party Integrations\ParseManager.cs(432,32): error CS0433: El tipo 'System.Threading.Tasks.Task' existe tanto en 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5.1\System.Threading.Tasks.dll' como en 'c:\Users\...\Assets\Parse\Parse.Unity.dll'

Aparently Parse.dll has a definition of System.threading.tasks. But I need to use tasks in my code so I must import the same dll.
I'm using Unity 5.3, windows phone sdk 8.1 updated and Parse 1.6.2.
Are there any workaround to this issue? or another Parse.Unity.dll compatible with Windows phone in unity that I can use?

Thanks.

**Comment by richardjrossiii** [comment]
Because Unity on Windows Phone platforms uses the built-in .NET Framework, instead of the mono 2.0-based solution, you'll have to fork & re-compile the SDK yourself without our tasks framework included. You should just be able to exclude the 'tasks' folder from the `Parse.Unity.csproj` project and compile.

Unfortunately Unity on windows phone is sort of a second-class citizen, as it has nowhere near the adoption as Unity does on iOS and Android.

With our current NuGet distribution, there's no way for us to currently support this workflow, sadly.

If you have any issues with this workflow feel free to re-open the issue.

**Comment by sercante** [comment]
I'm afraid it's going to be more complex  than just excluding the Tasks folder in the Parse.unity project, the reference of System.Threading.Taks is being used by the rest of the code and without the classes it can't fulfill the reference. I was able add the reference manually to the same location I'm using from Unity and build the dll, but the same error appears in Unity.

Since I'm not quite experienced in Visual I don't know if I'm loosing something in order to bypass the Task reference. 

So again, thanks for Help.

**Comment by richardjrossiii** [comment]
We are currently working on support for Unity in the context of windows phone, but it's still not a supported platform yet. In order to do so we will have to change how we reference `System.Threading.Tasks`, you are correct.

Unfortunately we do not have an ETA at this time for supporting Unity and WindowsPhone.
